### ISSUE TITLE
tokenSupply from the subgraph is not equal to totalSupply from the token contract

### ISSUE THREAD

**Issue by pre-vail** [Float-Capital/contracts#1]
for example, using the latest graph
https://thegraph.com/hosted-service/subgraph/float-capital/dev-graph-two?version=pending
this query
`
{
  syntheticTokens(
    where: {id: "0x97b0ba4a8ba02b8d002c156a7bedbf5264cc0f7a"}
  ) {
    tokenSupply
    tokenType
  }
}
`
yields this result
`
{
  "data": {
    "syntheticTokens": [
      {
        "tokenSupply": "5026091841454294963960495",
        "tokenType": "Short"
      }
    ]
  }
}
`
but the contract for this token ([3th short](https://polygonscan.com/address/0x97B0Ba4a8Ba02B8d002C156a7BEdBF5264CC0f7A#readProxyContract)) gives a totalSupply of: 132273294895389976249702

**Comment by Stentonian** [comment]
Thanks @pre-vail. Moved to https://github.com/Float-Capital/monorepo/issues/2811
